all:
  children:
    servers:
      children:
        EC2Group1:
          hosts:
            Ansible-Exercise0:
              ansible_host: 3.70.112.36
              ansible_ssh_common_args: -o StrictHostKeyChecking=no
              ansible_ssh_private_key_file: ~/.ssh/key-activ.pem
              ansible_user: ubuntu
        EC2Group2:
          hosts:
            Ansible-Exercise1:
              ansible_host: 18.184.94.63
              ansible_ssh_common_args: -o StrictHostKeyChecking=no
              ansible_ssh_private_key_file: ~/.ssh/key-activ.pem
              ansible_user: ubuntu
        EC2Group3:
          hosts:
            Ansible-Exercise2:
              ansible_host: 18.197.69.140
              ansible_ssh_common_args: -o StrictHostKeyChecking=no
              ansible_ssh_private_key_file: ~/.ssh/key-activ.pem
              ansible_user: ubuntu
